[package]
name = "matt/zepsgame"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Dataservice = "leifstout/dataservice@1.0.0"
Networker = "leifstout/networker@0.3.1"